### ISSUE TITLE
Diseño del modelo de la Base de Datos para gestión de tipos de novedades.

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_crud#21]
Realizar el rediseño de la base de datos para lograr gestionar los tipos de novedades, contemplando las modificación y agregación de tablas y atributos, según lo analizado en [Issue #30](https://github.com/udistrital/cumplidos_mid/issues/30)

**Criterio de aceptación**

- [x] Modelo de la BD rediseñado.

**Comment by ricardoavendano** [comment]
Se inicia el diseño y desarrollo de las tablas necesarias para gestionar los tipos de novedades y documentos solicitados

**Comment by ricardoavendano** [comment]
![modelo](https://user-images.githubusercontent.com/51935170/133044815-afa7bfd8-55b1-47c9-9035-b7a8c7c5f0e9.png)
Se ajusta modelo E-R con las nuevas tablas documentos_contrato y soportes:

--Tabla documentos_contrato
CREATE TABLE argo.documentos_contrato (
	id int4 NOT NULL, -- identificador unico del documento registrado 
	enlace varchar NOT NULL, -- enlace documento nuxeo
	id_documento int4 NOT NULL, -- id documento api documentos
	fecha_registro date NOT NULL DEFAULT 'now'::text::date, -- fecha de registro del documento
	id_novedades_poscontractuales int4 NOT NULL, --id tabla novedades_poscontractuales
	CONSTRAINT pk_doc_contrato PRIMARY KEY (id)
);

ALTER TABLE argo.documentos_contrato ADD CONSTRAINT fk_contrato_general_documentos FOREIGN KEY (id_novedades_poscontractuales) REFERENCES argo.novedades_poscontractuales(id) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE SEQUENCE argo.documentos_contrato_seq
	NO MINVALUE
	NO maxvalue;
COMMENT ON SEQUENCE documentos_contrato_seq IS 'secuencia para tabla documentos_contrato';


COMMENT ON COLUMN argo.documentos_contrato.id IS 'identificador unico del documento registrado';
COMMENT ON COLUMN argo.documentos_contrato.enlace IS 'enlace documento nuxeo';
COMMENT ON COLUMN argo.documentos_contrato.id_documento IS 'id documento api documentos';
COMMENT ON COLUMN argo.documentos_contrato.fecha_registro IS 'fecha de registro del documento';
COMMENT ON COLUMN argo.documentos_contrato.id_novedades_poscontractuales IS 'id tabla novedades_poscontractuales';

COMMENT ON CONSTRAINT fk_contrato_general_documentos ON argo.documentos_contrato IS 'llave foranea que referencia a la tabla novedades_poscontractuales';

ALTER TABLE argo.documentos_contrato OWNER TO postgres;
GRANT ALL ON TABLE argo.documentos_contrato TO postgres;
GRANT ALL ON TABLE argo.documentos_contrato TO desarrollooas;


--Tabla soportes
CREATE TABLE argo.soportes (
	id int4 NOT NULL, -- identificador unico del documento registrado 
	enlace varchar NOT NULL, -- enlace documento nuxeo
	id_documento int4 NOT NULL, -- id documento api documentos
	fecha_registro date NOT NULL DEFAULT 'now'::text::date, -- fecha de registro del soporte
	id_novedades_poscontractuales int4 NOT NULL, --id tabla novedades_poscontractuales
	CONSTRAINT pk_soporte_contrato PRIMARY KEY (id)
);

ALTER TABLE argo.soportes ADD CONSTRAINT fk_contrato_general_soportes FOREIGN KEY (id_novedades_poscontractuales) REFERENCES argo.novedades_poscontractuales(id) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE SEQUENCE argo.soportes_contrato_seq
	NO MINVALUE
	NO maxvalue;
COMMENT ON SEQUENCE soportes_contrato_seq IS 'secuencia para tabla soportes';


COMMENT ON COLUMN argo.soportes.id IS 'identificador unico del soporte registrado';
COMMENT ON COLUMN argo.soportes.enlace IS 'enlace documento nuxeo';
COMMENT ON COLUMN argo.soportes.id_documento IS 'id documento api documentos';
COMMENT ON COLUMN argo.soportes.fecha_registro IS 'fecha de registro del documento';
COMMENT ON COLUMN argo.soportes.id_novedades_poscontractuales IS 'id tabla novedades_poscontractuales';

COMMENT ON CONSTRAINT fk_contrato_general_soportes ON argo.soportes IS 'llave foranea que referencia a la tabla novedades_poscontractuales';

ALTER TABLE argo.soportes OWNER TO postgres;
GRANT ALL ON TABLE argo.soportes TO postgres;
GRANT ALL ON TABLE argo.soportes TO desarrollooas;

**Comment by a52290451** [comment]
Queda pendiente validación y carga del modelo.

**Comment by a52290451** [comment]
Se descarta el modelo planteado al utilizar el API gestor_documental_mid.
